---

- hosts: ngcs_devices
  collections:
    - opengear_om.om
  connection: httpapi
  gather_facts: no
  tasks:
    - name: Add conn
      opengear.om.om_conns:
        config:
        - ipv4_static_settings:
            netmask: 255.255.255.0
            address: 10.10.200.10
          mode: static
          physif: net1
        state:
          merged