---

- hosts: ngcs_devices
  collections:
    - opengear_om.om
  connection: httpapi
  gather_facts: no
  tasks:
    - name: Delete user
      opengear.om.om_users:
        config:
        - username: test1
        - username: test2
        state:
          deleted