---

- hosts: ngcsdevices
  collections:
    - opengear_om.om
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Delete groups
      opengear.om.om_groups:
        config:
        - groupname: test4
        - groupname: test5
        - groupname: test7
        state:
          deleted