---

- hosts: ngcs_devices
  collections:
    - opengear_om.om
  connection: httpapi
  tasks:
    - name: Add groups
      opengear.om.om_groups:
        config:
        - groupname: test4
          enabled: yes
          mode: global
          role: Administrator
          description: This group was changed.
        - groupname: test5
          enabled: no
          mode: global
          role: Administrator
          description: This group was added.
        - groupname: test7
          enabled: yes
          description: This group was added.
          role: ConsoleUser
          mode: scoped
          ports:
          - serial/by-opengear-id/port01
          - serial/by-opengear-id/port02
          - serial/by-opengear-id/port03
        state:
          merged