---

- hosts: ngcs_devices
  collections:
    - opengear_om.om
  connection: httpapi
  tasks:
    - name: Add Google NTP server
      opengear.om.om_services:
        config:
          ntp:
            enabled: yes
            servers:
            - value: 1.1.1.1
        state:
          overridden