---

- hosts: ngcs_devices
  collections:
    - opengear_om.om
  connection: httpapi
  gather_facts: no
  tasks:
    - name: Add user
      opengear.om.om_users:
        config:
        - username: test1
          enabled: no
          no_password: yes
          description: test1 user
        - username: test2
          enabled: yes
          no_password: yes
          description: test2 user
        state:
          overridden